//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCart_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartDetail
    {
        public int CartId { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    
        public virtual ItemDetail ItemDetail { get; set; }
    }
}
